# Generated by Django 4.0.5 on 2022-07-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='name',
            field=models.CharField(max_length=55, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='prenom',
            field=models.CharField(max_length=55, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
