# Generated by Django 4.0.5 on 2022-07-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blog_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.auteur'),
        ),
    ]
